version: '2'
services:

  example-viron-page-definer:
    # 240*1024*1024 = 251658240 Byte = 240 MB
    mem_limit: 251658240
    build: .
    working_dir: "/example-viron-page-definer"
    depends_on:
      - mysql
    ports:
      - 3000:3000
      - 53000:53000
    environment:
      - SERVICE_ENV=local
      - GOOGLE_OAUTH_CLIENT_ID=${GOOGLE_OAUTH_CLIENT_ID}
      - GOOGLE_OAUTH_CLIENT_SECRET=${GOOGLE_OAUTH_CLIENT_SECRET}
    volumes:
      - $PWD/package.json:/example-viron-page-definer/package.json
      - $PWD/shared:/example-viron-page-definer/shared
      - $PWD/config:/example-viron-page-definer/config
      - $PWD/app.js:/example-viron-page-definer/app.js
      - $PWD/controllers:/example-viron-page-definer/controllers
      - $PWD/fittings:/example-viron-page-definer/fittings
      - $PWD/swagger:/example-viron-page-definer/swagger
      - $PWD/test:/example-viron-page-definer/test
      - $PWD/.env:/example-viron-page-definer/.env
    command: npm run inspect

  mysql:
    # 512*1024*1024 = 536870912 Byte = 512 MB
    mem_limit: 536870912
    image: mysql:5.6
    ports:
      - 3306:3306
    volumes:
      - $PWD/docker/mysql/data:/var/lib/mysql
    env_file:
      - ./mysql.env
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    networks:
      default:
        aliases:
          - viron.dev
